CREATE TABLE IF NOT EXISTS TASK_CHAT_PARTICIPANT (
  id        SERIAL PRIMARY KEY,
  taskid    INTEGER NOT NULL REFERENCES TASK(taskid) ON DELETE CASCADE,
  userid    INTEGER NOT NULL REFERENCES "USER"(userid) ON DELETE CASCADE,
  addedby   INTEGER REFERENCES "USER"(userid),
  addedat   TIMESTAMP DEFAULT NOW(),
  UNIQUE(taskid, userid)
);
